### ISSUE TITLE
Is it possible to increase the number of points using SGolay?

### ISSUE THREAD

**Issue by Cram3r95** [espdev/sgolay2#4]
I want to estimate the velocity and acceleration given some observation data. Despite the fact that this filter works quite well, is it possible to go from 20 noisy points (assuming the sampling frequency is 10 Hz) to 40 SGolay filtered points, assuming the sampling frequency is 20 Hz, in order to compute the velocity and acceleration? Since we need a fixed period.

**Comment by espdev** [comment]
If I understand correctly, you need interpolation. Savitzky–Golay is just a digital filter via convolution, not an interpolator.
