### ISSUE TITLE
question about 'np.fliplr' in '_compute_kernel' method

### ISSUE THREAD

**Issue by lxxh97** [espdev/sgolay2#5]
After reading the code, I have been puzzled by a problem that I can't solve after thinking for a long time: why use 'np.fliplr' in '_compute_kernel' method?

**Comment by espdev** [comment]
Hi @lxxh97,

I don't remember, to be honest. You can try experimenting with this, remove fliplr and see what happens. Try also to replace correlation with convolution.

**Comment by lxxh97** [comment]
Thanks a lot.  Actually I've tried before, so I'm confused. But I am worried about whether my verification is wrong, so I come to ask you. Thank you again!

**Comment by espdev** [comment]
You are welcome. Also if you want to improve the code, a PR welcome! :)
